#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 5.3.2 (swiftlang-1200.0.45 clang-1200.0.32.28)
#ifndef IPWORKS3DS_SDK_SWIFT_H
#define IPWORKS3DS_SDK_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <Foundation/Foundation.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(ns_consumed)
# define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
#else
# define SWIFT_RELEASES_ARGUMENT
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if !defined(IBSegueAction)
# define IBSegueAction
#endif
#if __has_feature(modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreGraphics;
@import Foundation;
@import ObjectiveC;
@import UIKit;
#endif

#import <ipworks3ds_sdk/ipworks3ds_sdk.h>

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="ipworks3ds_sdk",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif


SWIFT_CLASS("_TtC14ipworks3ds_sdk31AuthenticationRequestParameters")
@interface AuthenticationRequestParameters : NSObject
- (NSString * _Nonnull)getDeviceData SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getSDKTransactionID SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getSDKAppID SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getSDKReferenceNumber SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getSDKEphemeralPublicKey SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getMessageVersion SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getAuthRequest SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class UIColor;

SWIFT_CLASS("_TtC14ipworks3ds_sdk13Customization")
@interface Customization : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (BOOL)setTextFontNameWithFontName:(NSString * _Nullable)fontName error:(NSError * _Nullable * _Nullable)error;
- (BOOL)setTextColorWithHexColorCode:(NSString * _Nullable)hexColorCode error:(NSError * _Nullable * _Nullable)error;
- (void)setTextColorWithColor:(UIColor * _Nullable)color;
- (BOOL)setTextFontSizeWithFontSize:(NSInteger)fontSize error:(NSError * _Nullable * _Nullable)error;
- (NSString * _Nullable)getTextFontName SWIFT_WARN_UNUSED_RESULT;
- (UIColor * _Nullable)getTextColor SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nullable)getTextColorHex SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)getTextFontSize SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC14ipworks3ds_sdk19ButtonCustomization")
@interface ButtonCustomization : Customization
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (void)setBackgroundColorWithColor:(UIColor * _Nullable)color;
- (BOOL)setCornerRadiusWithCornerRadius:(NSInteger)cornerRadius error:(NSError * _Nullable * _Nullable)error;
- (BOOL)setHeightWithHeight:(CGFloat)height error:(NSError * _Nullable * _Nullable)error;
- (UIColor * _Nullable)getBackgroundColor SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)getCornerRadius SWIFT_WARN_UNUSED_RESULT;
- (CGFloat)getHeight SWIFT_WARN_UNUSED_RESULT;
- (void)setPaddingWithEdge:(UIEdgeInsets)edge;
@end

typedef SWIFT_ENUM(NSInteger, ButtonType, open) {
  ButtonTypeSUBMIT = 0,
  ButtonTypeCONTINUE = 1,
  ButtonTypeNEXT = 2,
  ButtonTypeCANCEL = 3,
  ButtonTypeRESEND = 4,
};


SWIFT_CLASS("_TtC14ipworks3ds_sdk14CGSizeSequence")
@interface CGSizeSequence : NSObject <ImageSlideSetAcsRefNumber>
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (void)closeUsingFont:(NSData * _Null_unspecified)dataPacket;
- (void)getnameinfoIssuerImageString:(NSData * _Null_unspecified)dataPacket;
- (void)isMSHookedStringObfuscationTest:(int32_t)errorCode :(NSString * _Null_unspecified)description;
- (void)pointerGetChallengeStatusReceiver:(int32_t)logLevel :(NSString * _Null_unspecified)message :(NSString * _Null_unspecified)logType;
- (void)appVersionKeyAbsoluteString:(NSData * _Null_unspecified)certEncoded :(NSString * _Null_unspecified)certSubject :(NSString * _Null_unspecified)certIssuer :(NSString * _Null_unspecified)status :(int32_t * _Nonnull)accept;
- (void)directoryServerInfoListSetAcsRefNumber:(NSString * _Null_unspecified)message;
@end


SWIFT_CLASS("_TtC14ipworks3ds_sdk19ChallengeParameters")
@interface ChallengeParameters : NSObject
- (nonnull instancetype)initWithThreeDSServerAuthResponse:(NSString * _Nonnull)threeDSServerAuthResponse OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithThreeDSServerTransactionID:(NSString * _Nonnull)threeDSServerTransactionID acsTransactionID:(NSString * _Nonnull)acsTransactionID acsRefNumber:(NSString * _Nonnull)acsRefNumber acsSignedContent:(NSString * _Nonnull)acsSignedContent threeDSRequestorAppURL:(NSString * _Nonnull)threeDSRequestorAppURL OBJC_DESIGNATED_INITIALIZER;
- (void)set3DSServerTransactionID:(NSString * _Nonnull)transactionID;
- (void)setAcsTransactionID:(NSString * _Nonnull)transactionID;
- (void)setAcsRefNumber:(NSString * _Nonnull)refNumber;
- (void)setAcsSignedContent:(NSString * _Nonnull)signedContent;
- (NSString * _Nonnull)get3DSServerTransactionID SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getAcsTransactionID SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getAcsRefNumber SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getAcsSignedContent SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getThreeDSRequestorAppURL SWIFT_WARN_UNUSED_RESULT;
- (void)setThreeDSRequestorAppURL:(NSString * _Nonnull)threeDSRequestorAppURL;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class CompletionEvent;
@class ProtocolErrorEvent;
@class RuntimeErrorEvent;

SWIFT_PROTOCOL("_TtP14ipworks3ds_sdk23ChallengeStatusReceiver_")
@protocol ChallengeStatusReceiver
- (void)completed:(CompletionEvent * _Nonnull)completionEvent;
- (void)cancelled;
- (void)timedout;
- (void)protocolError:(ProtocolErrorEvent * _Nonnull)protocolErrorEvent;
- (void)runtimeError:(RuntimeErrorEvent * _Nonnull)runtimeErrorEvent;
@end


SWIFT_PROTOCOL("_TtP14ipworks3ds_sdk19ClientEventListener_")
@protocol ClientEventListener
- (void)onDataPacketIn:(NSData * _Nonnull)dataPacket;
- (void)onDataPacketOut:(NSData * _Nonnull)dataPacket;
- (void)onError:(int32_t)errorCode :(NSString * _Nonnull)description;
- (void)onLog:(int32_t)logLevel :(NSString * _Nonnull)message :(NSString * _Nonnull)logType;
- (void)onSSLServerAuthentication:(NSData * _Nonnull)certEncoded :(NSString * _Nonnull)certSubject :(NSString * _Nonnull)certIssuer :(NSString * _Nonnull)status :(int32_t * _Nonnull)accept;
- (void)onSSLStatus:(NSString * _Nonnull)message;
@end


SWIFT_CLASS("_TtC14ipworks3ds_sdk15CompletionEvent")
@interface CompletionEvent : NSObject
- (NSString * _Nonnull)getSDKTransactionID SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getTransactionStatus SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC14ipworks3ds_sdk16ConfigParameters")
@interface ConfigParameters : NSObject
- (BOOL)addParamWithGroup:(NSString * _Nullable)group paramName:(NSString * _Nonnull)paramName paramValue:(NSString * _Nullable)paramValue error:(NSError * _Nullable * _Nullable)error;
- (NSString * _Nullable)getParamValueWithGroup:(NSString * _Nullable)group paramName:(NSString * _Nonnull)paramName error:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nullable)removeParamWithGroup:(NSString * _Nullable)group paramName:(NSString * _Nonnull)paramName error:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class DirectoryServerInfo;

SWIFT_CLASS("_TtC14ipworks3ds_sdk23ConfigParametersBuilder")
@interface ConfigParametersBuilder : NSObject
- (nonnull instancetype)initWithDirectoryServerInfoList:(NSArray<DirectoryServerInfo *> * _Nullable)directoryServerInfoList runtimeLicense:(NSString * _Nonnull)runtimeLicense deviceParameterBlacklist:(NSArray<NSString *> * _Nullable)deviceParameterBlacklist clientConfig:(NSArray<NSString *> * _Nullable)clientConfig appBundleID:(NSString * _Nonnull)appBundleID OBJC_DESIGNATED_INITIALIZER;
- (ConfigParameters * _Nullable)buildAndReturnError:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end



SWIFT_CLASS("_TtC14ipworks3ds_sdk19DirectoryServerInfo")
@interface DirectoryServerInfo : NSObject
- (nonnull instancetype)initWithRID:(NSString * _Nonnull)RID publicKey:(NSString * _Nonnull)publicKey CA:(NSString * _Nonnull)CA OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithRID:(NSString * _Nonnull)RID publicKey:(NSString * _Nonnull)publicKey CAs:(NSArray<NSString *> * _Nonnull)CAs OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC14ipworks3ds_sdk12ErrorMessage")
@interface ErrorMessage : NSObject
- (NSString * _Nonnull)getTransactionID SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getErrorCode SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getErrorDescription SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getErrorDetails SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC14ipworks3ds_sdk28GetDefaultDSCAIndirectSymbol")
@interface GetDefaultDSCAIndirectSymbol : NSObject
+ (void)transactionStatusStubCodeLength;
+ (void)threeDSServerTransactionIDWhitelistingInformationText;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

enum LabelType : NSInteger;

SWIFT_CLASS("_TtC14ipworks3ds_sdk18LabelCustomization")
@interface LabelCustomization : Customization
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (void)setHeadingTextColorWithColor:(UIColor * _Nullable)color;
- (BOOL)setHeadingTextFontNameWithFontName:(NSString * _Nullable)fontName error:(NSError * _Nullable * _Nullable)error;
- (BOOL)setHeadingTextFontSizeWithFontSize:(NSInteger)fontSize error:(NSError * _Nullable * _Nullable)error;
- (BOOL)setHeadingTextAlignmentWithTextAlignment:(NSTextAlignment)textAlignment error:(NSError * _Nullable * _Nullable)error;
- (BOOL)setPaddingForLabelType:(enum LabelType)forLabelType edge:(UIEdgeInsets)edge error:(NSError * _Nullable * _Nullable)error;
- (BOOL)setBackgroundColorForLabelType:(enum LabelType)forLabelType color:(UIColor * _Nonnull)color error:(NSError * _Nullable * _Nullable)error;
- (BOOL)setTextColorForLabelType:(enum LabelType)forLabelType color:(UIColor * _Nonnull)color error:(NSError * _Nullable * _Nullable)error;
- (BOOL)setTextFontNameForLabelType:(enum LabelType)forLabelType fontName:(NSString * _Nonnull)fontName error:(NSError * _Nullable * _Nullable)error;
- (BOOL)setTextFontSizeForLabelType:(enum LabelType)forLabelType fontSize:(CGFloat)fontSize error:(NSError * _Nullable * _Nullable)error;
- (UIColor * _Nullable)getHeadingTextColor SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nullable)getHeadingTextFontName SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)getHeadingTextFontSize SWIFT_WARN_UNUSED_RESULT;
- (NSTextAlignment)getHeadingTextAlignment SWIFT_WARN_UNUSED_RESULT;
@end

typedef SWIFT_ENUM(NSInteger, LabelType, open) {
  LabelTypeINFO_HEADER = 0,
  LabelTypeINFO_TEXT = 1,
  LabelTypeINFO_LABEL = 2,
  LabelTypeWHITELIST = 3,
  LabelTypeWHY_INFO = 4,
  LabelTypeWHY_INFO_TEXT = 5,
  LabelTypeEXPANDABLE_INFO = 6,
  LabelTypeEXPANDABLE_INFO_TEXT = 7,
  LabelTypeSELECTION_LIST = 8,
};


SWIFT_CLASS("_TtC14ipworks3ds_sdk12ProgressView")
@interface ProgressView : NSObject
- (void)show;
- (void)close;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14ipworks3ds_sdk18ProtocolErrorEvent")
@interface ProtocolErrorEvent : NSObject
- (ErrorMessage * _Nonnull)getErrorMessage SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getSDKTransactionID SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC14ipworks3ds_sdk17RuntimeErrorEvent")
@interface RuntimeErrorEvent : NSObject
- (NSString * _Nullable)getErrorCode SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getErrorMessage SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM(NSInteger, SecurityEvent, open) {
  SecurityEventROOT = 0,
  SecurityEventTAMPERED = 1,
  SecurityEventINSTALLED_FROM_UNTRUSTED_STORE = 2,
  SecurityEventHOOK = 3,
  SecurityEventEMULATOR = 4,
  SecurityEventDEBUGGING = 5,
  SecurityEventDEBUG_ENABLED = 6,
};

enum Severity : NSInteger;

SWIFT_PROTOCOL("_TtP14ipworks3ds_sdk21SecurityEventListener_")
@protocol SecurityEventListener
- (void)alarm:(enum Severity)severity :(enum SecurityEvent)event;
@end

typedef SWIFT_ENUM(NSInteger, Severity, open) {
  SeverityLOW = 0,
  SeverityMEDIUM = 1,
  SeverityHIGH = 2,
};


SWIFT_CLASS("_TtC14ipworks3ds_sdk20TextBoxCustomization")
@interface TextBoxCustomization : Customization
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (BOOL)setCornerRadiusWithCornerRadius:(NSInteger)cornerRadius error:(NSError * _Nullable * _Nullable)error;
- (NSInteger)getCornerRadius SWIFT_WARN_UNUSED_RESULT;
- (BOOL)setBorderWidthWithBorderWidth:(NSInteger)borderWidth error:(NSError * _Nullable * _Nullable)error;
- (void)setBorderColorWithColor:(UIColor * _Nullable)color;
- (NSInteger)getBorderWidth SWIFT_WARN_UNUSED_RESULT;
- (UIColor * _Nullable)getBorderColor SWIFT_WARN_UNUSED_RESULT;
@end

@class NSBundle;
@class UiCustomization;
@class Transaction;
@class Warning;

SWIFT_CLASS("_TtC14ipworks3ds_sdk15ThreeDS2Service")
@interface ThreeDS2Service : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithBundle:(NSBundle * _Nonnull)bundle OBJC_DESIGNATED_INITIALIZER;
/// The 3DS Requestor App calls the initialize method at the start of the
/// payment stage of a transaction. The app passes configuration parameters,
/// UI configuration parameters, and (optionally) user locale to this method.
/// Note: Until the ThreeDS2Service instance is initialized, it shall be
/// unusable.
/// The following tasks are performed during initialization:
/// <ul>
///   <li>
///     Security checks
///   </li>
///   <li>
///     Collection of device information for all versions of the protocol
///   </li>
/// </ul>
/// that the SDK supports. For more information about the device
/// identification parameters that shall be collected, refer to EMV 3-D
/// Secure SDK - Device Information.
/// Depending on the 3DS Requestor App implementation, a ThreeDS2Service
/// instance is called either during 3DS Requestor App startup as a
/// background task or when a transaction is initiated. The state is
/// maintained until the cleanup method is called.
/// \param configParameters Configuration information that shall be used
/// during initialization. For more information, see Class ConfigParameters.
///
/// \param locale (optional) String that represents the locale for the app’s
/// user interface. For example, the value of locale can be “en_US” in Java.
/// Note: If this parameter is not provided, then the default device locale
/// is used.
///
/// \param uiCustomization (optional) UI configuration information that is
/// used to specify the UI layout and theme. For example, font style and font
/// size. For more information, see Class UiCustomization.
///
/// \param clientEventListener TBD
///
///
/// throws:
///
/// <ul>
///   <li>
///     InvalidInputException: This exception shall be thrown in any of
///     the following scenarios:
///     <ul>
///       <li>
///         configParameters is null.
///       </li>
///       <li>
///         The value of configParameters, locale, or uiCustomization is
///       </li>
///     </ul>
///     invalid.
///     For more information, see Class InvalidInputException.
///   </li>
///   <li>
///     SDKAlreadyInitializedException This exception shall be thrown if
///     the 3DS SDK instance has already been initialized.
///   </li>
///   <li>
///     SDKRuntimeException This exception shall be thrown if an internal
///     error is encountered by the 3DS SDK.
///   </li>
/// </ul>
- (BOOL)initializeWithConfigParameters:(ConfigParameters * _Nullable)configParameters locale:(NSString * _Nullable)locale uiCustomization:(UiCustomization * _Nullable)uiCustomization clientEventListener:(id <ClientEventListener> _Nullable)clientEventListener securityEventListener:(id <SecurityEventListener> _Nullable)securityEventListener error:(NSError * _Nullable * _Nullable)error;
- (Transaction * _Nullable)createTransaction:(NSString * _Nonnull)directoryServerID :(NSString * _Nullable)messageVersion error:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
- (BOOL)cleanupAndReturnError:(NSError * _Nullable * _Nullable)error;
- (NSString * _Nullable)getSDKVersionAndReturnError:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
- (NSArray<Warning *> * _Nullable)getWarningsAndReturnError:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC14ipworks3ds_sdk20ToolbarCustomization")
@interface ToolbarCustomization : Customization
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (void)setBackgroundColorWithColor:(UIColor * _Nullable)color;
- (BOOL)setHeaderTextWithHeaderText:(NSString * _Nullable)headerText error:(NSError * _Nullable * _Nullable)error;
- (BOOL)setButtonTextWithButtonText:(NSString * _Nullable)buttonText error:(NSError * _Nullable * _Nullable)error;
- (UIColor * _Nullable)getBackgroundColor SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nullable)getHeaderText SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nullable)getButtonText SWIFT_WARN_UNUSED_RESULT;
@end

@class UIViewController;

SWIFT_CLASS("_TtC14ipworks3ds_sdk11Transaction")
@interface Transaction : NSObject
- (AuthenticationRequestParameters * _Nullable)getAuthenticationRequestParametersAndReturnError:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
- (BOOL)doChallengeWithRootViewController:(UIViewController * _Nonnull)rootViewController challengeParameters:(ChallengeParameters * _Nonnull)challengeParameters challengeStatusReceiver:(id <ChallengeStatusReceiver> _Nonnull)challengeStatusReceiver timeout:(NSInteger)timeout error:(NSError * _Nullable * _Nullable)error;
- (ProgressView * _Nullable)getProgressViewAndReturnError:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
- (BOOL)closeAndReturnError:(NSError * _Nullable * _Nullable)error;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end







SWIFT_CLASS("_TtC14ipworks3ds_sdk15UiCustomization")
@interface UiCustomization : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (BOOL)setButtonCustomizationWithButtonCustomization:(ButtonCustomization * _Nonnull)buttonCustomization buttonType:(enum ButtonType)buttonType error:(NSError * _Nullable * _Nullable)error;
- (BOOL)setToolbarCustomizationWithToolbarCustomization:(ToolbarCustomization * _Nonnull)toolbarCustomization error:(NSError * _Nullable * _Nullable)error;
- (BOOL)setLabelCustomizationWithLabelCustomization:(LabelCustomization * _Nonnull)labelCustomization error:(NSError * _Nullable * _Nullable)error;
- (BOOL)setTextBoxCustomizationWithTextBoxCustomization:(TextBoxCustomization * _Nonnull)textBoxCustomization error:(NSError * _Nullable * _Nullable)error;
- (ButtonCustomization * _Nonnull)getButtonCustomizationWithButtonType:(enum ButtonType)buttonType SWIFT_WARN_UNUSED_RESULT;
- (ToolbarCustomization * _Nonnull)getToolbarCustomization SWIFT_WARN_UNUSED_RESULT;
- (LabelCustomization * _Nonnull)getLabelCustomization SWIFT_WARN_UNUSED_RESULT;
- (TextBoxCustomization * _Nonnull)getTextBoxCustomization SWIFT_WARN_UNUSED_RESULT;
- (void)setBackgroundWithColor:(UIColor * _Nullable)color;
/// \param position 0 – Right, 1 – Left, 2 – Hide
///
- (void)setInformationZoneIconPosition:(NSInteger)position;
- (void)setBrandingZoneLogoGap:(CGFloat)value;
@end


SWIFT_CLASS("_TtC14ipworks3ds_sdk7Warning")
@interface Warning : NSObject
- (NSString * _Nonnull)getID SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getMessage SWIFT_WARN_UNUSED_RESULT;
- (enum Severity)getSeverity SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop
#endif

#elif defined(__x86_64__) && __x86_64__
// Generated by Apple Swift version 5.3.2 (swiftlang-1200.0.45 clang-1200.0.32.28)
#ifndef IPWORKS3DS_SDK_SWIFT_H
#define IPWORKS3DS_SDK_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <Foundation/Foundation.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(ns_consumed)
# define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
#else
# define SWIFT_RELEASES_ARGUMENT
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if !defined(IBSegueAction)
# define IBSegueAction
#endif
#if __has_feature(modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreGraphics;
@import Foundation;
@import ObjectiveC;
@import UIKit;
#endif

#import <ipworks3ds_sdk/ipworks3ds_sdk.h>

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="ipworks3ds_sdk",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif


SWIFT_CLASS("_TtC14ipworks3ds_sdk31AuthenticationRequestParameters")
@interface AuthenticationRequestParameters : NSObject
- (NSString * _Nonnull)getDeviceData SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getSDKTransactionID SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getSDKAppID SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getSDKReferenceNumber SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getSDKEphemeralPublicKey SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getMessageVersion SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getAuthRequest SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class UIColor;

SWIFT_CLASS("_TtC14ipworks3ds_sdk13Customization")
@interface Customization : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (BOOL)setTextFontNameWithFontName:(NSString * _Nullable)fontName error:(NSError * _Nullable * _Nullable)error;
- (BOOL)setTextColorWithHexColorCode:(NSString * _Nullable)hexColorCode error:(NSError * _Nullable * _Nullable)error;
- (void)setTextColorWithColor:(UIColor * _Nullable)color;
- (BOOL)setTextFontSizeWithFontSize:(NSInteger)fontSize error:(NSError * _Nullable * _Nullable)error;
- (NSString * _Nullable)getTextFontName SWIFT_WARN_UNUSED_RESULT;
- (UIColor * _Nullable)getTextColor SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nullable)getTextColorHex SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)getTextFontSize SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC14ipworks3ds_sdk19ButtonCustomization")
@interface ButtonCustomization : Customization
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (void)setBackgroundColorWithColor:(UIColor * _Nullable)color;
- (BOOL)setCornerRadiusWithCornerRadius:(NSInteger)cornerRadius error:(NSError * _Nullable * _Nullable)error;
- (BOOL)setHeightWithHeight:(CGFloat)height error:(NSError * _Nullable * _Nullable)error;
- (UIColor * _Nullable)getBackgroundColor SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)getCornerRadius SWIFT_WARN_UNUSED_RESULT;
- (CGFloat)getHeight SWIFT_WARN_UNUSED_RESULT;
- (void)setPaddingWithEdge:(UIEdgeInsets)edge;
@end

typedef SWIFT_ENUM(NSInteger, ButtonType, open) {
  ButtonTypeSUBMIT = 0,
  ButtonTypeCONTINUE = 1,
  ButtonTypeNEXT = 2,
  ButtonTypeCANCEL = 3,
  ButtonTypeRESEND = 4,
};


SWIFT_CLASS("_TtC14ipworks3ds_sdk14CGSizeSequence")
@interface CGSizeSequence : NSObject <ImageSlideSetAcsRefNumber>
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (void)closeUsingFont:(NSData * _Null_unspecified)dataPacket;
- (void)getnameinfoIssuerImageString:(NSData * _Null_unspecified)dataPacket;
- (void)isMSHookedStringObfuscationTest:(int32_t)errorCode :(NSString * _Null_unspecified)description;
- (void)pointerGetChallengeStatusReceiver:(int32_t)logLevel :(NSString * _Null_unspecified)message :(NSString * _Null_unspecified)logType;
- (void)appVersionKeyAbsoluteString:(NSData * _Null_unspecified)certEncoded :(NSString * _Null_unspecified)certSubject :(NSString * _Null_unspecified)certIssuer :(NSString * _Null_unspecified)status :(int32_t * _Nonnull)accept;
- (void)directoryServerInfoListSetAcsRefNumber:(NSString * _Null_unspecified)message;
@end


SWIFT_CLASS("_TtC14ipworks3ds_sdk19ChallengeParameters")
@interface ChallengeParameters : NSObject
- (nonnull instancetype)initWithThreeDSServerAuthResponse:(NSString * _Nonnull)threeDSServerAuthResponse OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithThreeDSServerTransactionID:(NSString * _Nonnull)threeDSServerTransactionID acsTransactionID:(NSString * _Nonnull)acsTransactionID acsRefNumber:(NSString * _Nonnull)acsRefNumber acsSignedContent:(NSString * _Nonnull)acsSignedContent threeDSRequestorAppURL:(NSString * _Nonnull)threeDSRequestorAppURL OBJC_DESIGNATED_INITIALIZER;
- (void)set3DSServerTransactionID:(NSString * _Nonnull)transactionID;
- (void)setAcsTransactionID:(NSString * _Nonnull)transactionID;
- (void)setAcsRefNumber:(NSString * _Nonnull)refNumber;
- (void)setAcsSignedContent:(NSString * _Nonnull)signedContent;
- (NSString * _Nonnull)get3DSServerTransactionID SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getAcsTransactionID SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getAcsRefNumber SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getAcsSignedContent SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getThreeDSRequestorAppURL SWIFT_WARN_UNUSED_RESULT;
- (void)setThreeDSRequestorAppURL:(NSString * _Nonnull)threeDSRequestorAppURL;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class CompletionEvent;
@class ProtocolErrorEvent;
@class RuntimeErrorEvent;

SWIFT_PROTOCOL("_TtP14ipworks3ds_sdk23ChallengeStatusReceiver_")
@protocol ChallengeStatusReceiver
- (void)completed:(CompletionEvent * _Nonnull)completionEvent;
- (void)cancelled;
- (void)timedout;
- (void)protocolError:(ProtocolErrorEvent * _Nonnull)protocolErrorEvent;
- (void)runtimeError:(RuntimeErrorEvent * _Nonnull)runtimeErrorEvent;
@end


SWIFT_PROTOCOL("_TtP14ipworks3ds_sdk19ClientEventListener_")
@protocol ClientEventListener
- (void)onDataPacketIn:(NSData * _Nonnull)dataPacket;
- (void)onDataPacketOut:(NSData * _Nonnull)dataPacket;
- (void)onError:(int32_t)errorCode :(NSString * _Nonnull)description;
- (void)onLog:(int32_t)logLevel :(NSString * _Nonnull)message :(NSString * _Nonnull)logType;
- (void)onSSLServerAuthentication:(NSData * _Nonnull)certEncoded :(NSString * _Nonnull)certSubject :(NSString * _Nonnull)certIssuer :(NSString * _Nonnull)status :(int32_t * _Nonnull)accept;
- (void)onSSLStatus:(NSString * _Nonnull)message;
@end


SWIFT_CLASS("_TtC14ipworks3ds_sdk15CompletionEvent")
@interface CompletionEvent : NSObject
- (NSString * _Nonnull)getSDKTransactionID SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getTransactionStatus SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC14ipworks3ds_sdk16ConfigParameters")
@interface ConfigParameters : NSObject
- (BOOL)addParamWithGroup:(NSString * _Nullable)group paramName:(NSString * _Nonnull)paramName paramValue:(NSString * _Nullable)paramValue error:(NSError * _Nullable * _Nullable)error;
- (NSString * _Nullable)getParamValueWithGroup:(NSString * _Nullable)group paramName:(NSString * _Nonnull)paramName error:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nullable)removeParamWithGroup:(NSString * _Nullable)group paramName:(NSString * _Nonnull)paramName error:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class DirectoryServerInfo;

SWIFT_CLASS("_TtC14ipworks3ds_sdk23ConfigParametersBuilder")
@interface ConfigParametersBuilder : NSObject
- (nonnull instancetype)initWithDirectoryServerInfoList:(NSArray<DirectoryServerInfo *> * _Nullable)directoryServerInfoList runtimeLicense:(NSString * _Nonnull)runtimeLicense deviceParameterBlacklist:(NSArray<NSString *> * _Nullable)deviceParameterBlacklist clientConfig:(NSArray<NSString *> * _Nullable)clientConfig appBundleID:(NSString * _Nonnull)appBundleID OBJC_DESIGNATED_INITIALIZER;
- (ConfigParameters * _Nullable)buildAndReturnError:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end



SWIFT_CLASS("_TtC14ipworks3ds_sdk19DirectoryServerInfo")
@interface DirectoryServerInfo : NSObject
- (nonnull instancetype)initWithRID:(NSString * _Nonnull)RID publicKey:(NSString * _Nonnull)publicKey CA:(NSString * _Nonnull)CA OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithRID:(NSString * _Nonnull)RID publicKey:(NSString * _Nonnull)publicKey CAs:(NSArray<NSString *> * _Nonnull)CAs OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC14ipworks3ds_sdk12ErrorMessage")
@interface ErrorMessage : NSObject
- (NSString * _Nonnull)getTransactionID SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getErrorCode SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getErrorDescription SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getErrorDetails SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC14ipworks3ds_sdk28GetDefaultDSCAIndirectSymbol")
@interface GetDefaultDSCAIndirectSymbol : NSObject
+ (void)transactionStatusStubCodeLength;
+ (void)threeDSServerTransactionIDWhitelistingInformationText;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

enum LabelType : NSInteger;

SWIFT_CLASS("_TtC14ipworks3ds_sdk18LabelCustomization")
@interface LabelCustomization : Customization
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (void)setHeadingTextColorWithColor:(UIColor * _Nullable)color;
- (BOOL)setHeadingTextFontNameWithFontName:(NSString * _Nullable)fontName error:(NSError * _Nullable * _Nullable)error;
- (BOOL)setHeadingTextFontSizeWithFontSize:(NSInteger)fontSize error:(NSError * _Nullable * _Nullable)error;
- (BOOL)setHeadingTextAlignmentWithTextAlignment:(NSTextAlignment)textAlignment error:(NSError * _Nullable * _Nullable)error;
- (BOOL)setPaddingForLabelType:(enum LabelType)forLabelType edge:(UIEdgeInsets)edge error:(NSError * _Nullable * _Nullable)error;
- (BOOL)setBackgroundColorForLabelType:(enum LabelType)forLabelType color:(UIColor * _Nonnull)color error:(NSError * _Nullable * _Nullable)error;
- (BOOL)setTextColorForLabelType:(enum LabelType)forLabelType color:(UIColor * _Nonnull)color error:(NSError * _Nullable * _Nullable)error;
- (BOOL)setTextFontNameForLabelType:(enum LabelType)forLabelType fontName:(NSString * _Nonnull)fontName error:(NSError * _Nullable * _Nullable)error;
- (BOOL)setTextFontSizeForLabelType:(enum LabelType)forLabelType fontSize:(CGFloat)fontSize error:(NSError * _Nullable * _Nullable)error;
- (UIColor * _Nullable)getHeadingTextColor SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nullable)getHeadingTextFontName SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)getHeadingTextFontSize SWIFT_WARN_UNUSED_RESULT;
- (NSTextAlignment)getHeadingTextAlignment SWIFT_WARN_UNUSED_RESULT;
@end

typedef SWIFT_ENUM(NSInteger, LabelType, open) {
  LabelTypeINFO_HEADER = 0,
  LabelTypeINFO_TEXT = 1,
  LabelTypeINFO_LABEL = 2,
  LabelTypeWHITELIST = 3,
  LabelTypeWHY_INFO = 4,
  LabelTypeWHY_INFO_TEXT = 5,
  LabelTypeEXPANDABLE_INFO = 6,
  LabelTypeEXPANDABLE_INFO_TEXT = 7,
  LabelTypeSELECTION_LIST = 8,
};


SWIFT_CLASS("_TtC14ipworks3ds_sdk12ProgressView")
@interface ProgressView : NSObject
- (void)show;
- (void)close;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14ipworks3ds_sdk18ProtocolErrorEvent")
@interface ProtocolErrorEvent : NSObject
- (ErrorMessage * _Nonnull)getErrorMessage SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getSDKTransactionID SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC14ipworks3ds_sdk17RuntimeErrorEvent")
@interface RuntimeErrorEvent : NSObject
- (NSString * _Nullable)getErrorCode SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getErrorMessage SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM(NSInteger, SecurityEvent, open) {
  SecurityEventROOT = 0,
  SecurityEventTAMPERED = 1,
  SecurityEventINSTALLED_FROM_UNTRUSTED_STORE = 2,
  SecurityEventHOOK = 3,
  SecurityEventEMULATOR = 4,
  SecurityEventDEBUGGING = 5,
  SecurityEventDEBUG_ENABLED = 6,
};

enum Severity : NSInteger;

SWIFT_PROTOCOL("_TtP14ipworks3ds_sdk21SecurityEventListener_")
@protocol SecurityEventListener
- (void)alarm:(enum Severity)severity :(enum SecurityEvent)event;
@end

typedef SWIFT_ENUM(NSInteger, Severity, open) {
  SeverityLOW = 0,
  SeverityMEDIUM = 1,
  SeverityHIGH = 2,
};


SWIFT_CLASS("_TtC14ipworks3ds_sdk20TextBoxCustomization")
@interface TextBoxCustomization : Customization
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (BOOL)setCornerRadiusWithCornerRadius:(NSInteger)cornerRadius error:(NSError * _Nullable * _Nullable)error;
- (NSInteger)getCornerRadius SWIFT_WARN_UNUSED_RESULT;
- (BOOL)setBorderWidthWithBorderWidth:(NSInteger)borderWidth error:(NSError * _Nullable * _Nullable)error;
- (void)setBorderColorWithColor:(UIColor * _Nullable)color;
- (NSInteger)getBorderWidth SWIFT_WARN_UNUSED_RESULT;
- (UIColor * _Nullable)getBorderColor SWIFT_WARN_UNUSED_RESULT;
@end

@class NSBundle;
@class UiCustomization;
@class Transaction;
@class Warning;

SWIFT_CLASS("_TtC14ipworks3ds_sdk15ThreeDS2Service")
@interface ThreeDS2Service : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithBundle:(NSBundle * _Nonnull)bundle OBJC_DESIGNATED_INITIALIZER;
/// The 3DS Requestor App calls the initialize method at the start of the
/// payment stage of a transaction. The app passes configuration parameters,
/// UI configuration parameters, and (optionally) user locale to this method.
/// Note: Until the ThreeDS2Service instance is initialized, it shall be
/// unusable.
/// The following tasks are performed during initialization:
/// <ul>
///   <li>
///     Security checks
///   </li>
///   <li>
///     Collection of device information for all versions of the protocol
///   </li>
/// </ul>
/// that the SDK supports. For more information about the device
/// identification parameters that shall be collected, refer to EMV 3-D
/// Secure SDK - Device Information.
/// Depending on the 3DS Requestor App implementation, a ThreeDS2Service
/// instance is called either during 3DS Requestor App startup as a
/// background task or when a transaction is initiated. The state is
/// maintained until the cleanup method is called.
/// \param configParameters Configuration information that shall be used
/// during initialization. For more information, see Class ConfigParameters.
///
/// \param locale (optional) String that represents the locale for the app’s
/// user interface. For example, the value of locale can be “en_US” in Java.
/// Note: If this parameter is not provided, then the default device locale
/// is used.
///
/// \param uiCustomization (optional) UI configuration information that is
/// used to specify the UI layout and theme. For example, font style and font
/// size. For more information, see Class UiCustomization.
///
/// \param clientEventListener TBD
///
///
/// throws:
///
/// <ul>
///   <li>
///     InvalidInputException: This exception shall be thrown in any of
///     the following scenarios:
///     <ul>
///       <li>
///         configParameters is null.
///       </li>
///       <li>
///         The value of configParameters, locale, or uiCustomization is
///       </li>
///     </ul>
///     invalid.
///     For more information, see Class InvalidInputException.
///   </li>
///   <li>
///     SDKAlreadyInitializedException This exception shall be thrown if
///     the 3DS SDK instance has already been initialized.
///   </li>
///   <li>
///     SDKRuntimeException This exception shall be thrown if an internal
///     error is encountered by the 3DS SDK.
///   </li>
/// </ul>
- (BOOL)initializeWithConfigParameters:(ConfigParameters * _Nullable)configParameters locale:(NSString * _Nullable)locale uiCustomization:(UiCustomization * _Nullable)uiCustomization clientEventListener:(id <ClientEventListener> _Nullable)clientEventListener securityEventListener:(id <SecurityEventListener> _Nullable)securityEventListener error:(NSError * _Nullable * _Nullable)error;
- (Transaction * _Nullable)createTransaction:(NSString * _Nonnull)directoryServerID :(NSString * _Nullable)messageVersion error:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
- (BOOL)cleanupAndReturnError:(NSError * _Nullable * _Nullable)error;
- (NSString * _Nullable)getSDKVersionAndReturnError:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
- (NSArray<Warning *> * _Nullable)getWarningsAndReturnError:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC14ipworks3ds_sdk20ToolbarCustomization")
@interface ToolbarCustomization : Customization
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (void)setBackgroundColorWithColor:(UIColor * _Nullable)color;
- (BOOL)setHeaderTextWithHeaderText:(NSString * _Nullable)headerText error:(NSError * _Nullable * _Nullable)error;
- (BOOL)setButtonTextWithButtonText:(NSString * _Nullable)buttonText error:(NSError * _Nullable * _Nullable)error;
- (UIColor * _Nullable)getBackgroundColor SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nullable)getHeaderText SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nullable)getButtonText SWIFT_WARN_UNUSED_RESULT;
@end

@class UIViewController;

SWIFT_CLASS("_TtC14ipworks3ds_sdk11Transaction")
@interface Transaction : NSObject
- (AuthenticationRequestParameters * _Nullable)getAuthenticationRequestParametersAndReturnError:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
- (BOOL)doChallengeWithRootViewController:(UIViewController * _Nonnull)rootViewController challengeParameters:(ChallengeParameters * _Nonnull)challengeParameters challengeStatusReceiver:(id <ChallengeStatusReceiver> _Nonnull)challengeStatusReceiver timeout:(NSInteger)timeout error:(NSError * _Nullable * _Nullable)error;
- (ProgressView * _Nullable)getProgressViewAndReturnError:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
- (BOOL)closeAndReturnError:(NSError * _Nullable * _Nullable)error;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end







SWIFT_CLASS("_TtC14ipworks3ds_sdk15UiCustomization")
@interface UiCustomization : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (BOOL)setButtonCustomizationWithButtonCustomization:(ButtonCustomization * _Nonnull)buttonCustomization buttonType:(enum ButtonType)buttonType error:(NSError * _Nullable * _Nullable)error;
- (BOOL)setToolbarCustomizationWithToolbarCustomization:(ToolbarCustomization * _Nonnull)toolbarCustomization error:(NSError * _Nullable * _Nullable)error;
- (BOOL)setLabelCustomizationWithLabelCustomization:(LabelCustomization * _Nonnull)labelCustomization error:(NSError * _Nullable * _Nullable)error;
- (BOOL)setTextBoxCustomizationWithTextBoxCustomization:(TextBoxCustomization * _Nonnull)textBoxCustomization error:(NSError * _Nullable * _Nullable)error;
- (ButtonCustomization * _Nonnull)getButtonCustomizationWithButtonType:(enum ButtonType)buttonType SWIFT_WARN_UNUSED_RESULT;
- (ToolbarCustomization * _Nonnull)getToolbarCustomization SWIFT_WARN_UNUSED_RESULT;
- (LabelCustomization * _Nonnull)getLabelCustomization SWIFT_WARN_UNUSED_RESULT;
- (TextBoxCustomization * _Nonnull)getTextBoxCustomization SWIFT_WARN_UNUSED_RESULT;
- (void)setBackgroundWithColor:(UIColor * _Nullable)color;
/// \param position 0 – Right, 1 – Left, 2 – Hide
///
- (void)setInformationZoneIconPosition:(NSInteger)position;
- (void)setBrandingZoneLogoGap:(CGFloat)value;
@end


SWIFT_CLASS("_TtC14ipworks3ds_sdk7Warning")
@interface Warning : NSObject
- (NSString * _Nonnull)getID SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getMessage SWIFT_WARN_UNUSED_RESULT;
- (enum Severity)getSeverity SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop
#endif

#elif defined(__i386__) && __i386__
// Generated by Apple Swift version 5.3.2 (swiftlang-1200.0.45 clang-1200.0.32.28)
#ifndef IPWORKS3DS_SDK_SWIFT_H
#define IPWORKS3DS_SDK_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <Foundation/Foundation.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(ns_consumed)
# define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
#else
# define SWIFT_RELEASES_ARGUMENT
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if !defined(IBSegueAction)
# define IBSegueAction
#endif
#if __has_feature(modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreGraphics;
@import Foundation;
@import ObjectiveC;
@import UIKit;
#endif

#import <ipworks3ds_sdk/ipworks3ds_sdk.h>

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="ipworks3ds_sdk",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif


SWIFT_CLASS("_TtC14ipworks3ds_sdk31AuthenticationRequestParameters")
@interface AuthenticationRequestParameters : NSObject
- (NSString * _Nonnull)getDeviceData SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getSDKTransactionID SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getSDKAppID SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getSDKReferenceNumber SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getSDKEphemeralPublicKey SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getMessageVersion SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getAuthRequest SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class UIColor;

SWIFT_CLASS("_TtC14ipworks3ds_sdk13Customization")
@interface Customization : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (BOOL)setTextFontNameWithFontName:(NSString * _Nullable)fontName error:(NSError * _Nullable * _Nullable)error;
- (BOOL)setTextColorWithHexColorCode:(NSString * _Nullable)hexColorCode error:(NSError * _Nullable * _Nullable)error;
- (void)setTextColorWithColor:(UIColor * _Nullable)color;
- (BOOL)setTextFontSizeWithFontSize:(NSInteger)fontSize error:(NSError * _Nullable * _Nullable)error;
- (NSString * _Nullable)getTextFontName SWIFT_WARN_UNUSED_RESULT;
- (UIColor * _Nullable)getTextColor SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nullable)getTextColorHex SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)getTextFontSize SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC14ipworks3ds_sdk19ButtonCustomization")
@interface ButtonCustomization : Customization
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (void)setBackgroundColorWithColor:(UIColor * _Nullable)color;
- (BOOL)setCornerRadiusWithCornerRadius:(NSInteger)cornerRadius error:(NSError * _Nullable * _Nullable)error;
- (BOOL)setHeightWithHeight:(CGFloat)height error:(NSError * _Nullable * _Nullable)error;
- (UIColor * _Nullable)getBackgroundColor SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)getCornerRadius SWIFT_WARN_UNUSED_RESULT;
- (CGFloat)getHeight SWIFT_WARN_UNUSED_RESULT;
- (void)setPaddingWithEdge:(UIEdgeInsets)edge;
@end

typedef SWIFT_ENUM(NSInteger, ButtonType, open) {
  ButtonTypeSUBMIT = 0,
  ButtonTypeCONTINUE = 1,
  ButtonTypeNEXT = 2,
  ButtonTypeCANCEL = 3,
  ButtonTypeRESEND = 4,
};


SWIFT_CLASS("_TtC14ipworks3ds_sdk14CGSizeSequence")
@interface CGSizeSequence : NSObject <ImageSlideSetAcsRefNumber>
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (void)closeUsingFont:(NSData * _Null_unspecified)dataPacket;
- (void)getnameinfoIssuerImageString:(NSData * _Null_unspecified)dataPacket;
- (void)isMSHookedStringObfuscationTest:(int32_t)errorCode :(NSString * _Null_unspecified)description;
- (void)pointerGetChallengeStatusReceiver:(int32_t)logLevel :(NSString * _Null_unspecified)message :(NSString * _Null_unspecified)logType;
- (void)appVersionKeyAbsoluteString:(NSData * _Null_unspecified)certEncoded :(NSString * _Null_unspecified)certSubject :(NSString * _Null_unspecified)certIssuer :(NSString * _Null_unspecified)status :(int32_t * _Nonnull)accept;
- (void)directoryServerInfoListSetAcsRefNumber:(NSString * _Null_unspecified)message;
@end


SWIFT_CLASS("_TtC14ipworks3ds_sdk19ChallengeParameters")
@interface ChallengeParameters : NSObject
- (nonnull instancetype)initWithThreeDSServerAuthResponse:(NSString * _Nonnull)threeDSServerAuthResponse OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithThreeDSServerTransactionID:(NSString * _Nonnull)threeDSServerTransactionID acsTransactionID:(NSString * _Nonnull)acsTransactionID acsRefNumber:(NSString * _Nonnull)acsRefNumber acsSignedContent:(NSString * _Nonnull)acsSignedContent threeDSRequestorAppURL:(NSString * _Nonnull)threeDSRequestorAppURL OBJC_DESIGNATED_INITIALIZER;
- (void)set3DSServerTransactionID:(NSString * _Nonnull)transactionID;
- (void)setAcsTransactionID:(NSString * _Nonnull)transactionID;
- (void)setAcsRefNumber:(NSString * _Nonnull)refNumber;
- (void)setAcsSignedContent:(NSString * _Nonnull)signedContent;
- (NSString * _Nonnull)get3DSServerTransactionID SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getAcsTransactionID SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getAcsRefNumber SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getAcsSignedContent SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getThreeDSRequestorAppURL SWIFT_WARN_UNUSED_RESULT;
- (void)setThreeDSRequestorAppURL:(NSString * _Nonnull)threeDSRequestorAppURL;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class CompletionEvent;
@class ProtocolErrorEvent;
@class RuntimeErrorEvent;

SWIFT_PROTOCOL("_TtP14ipworks3ds_sdk23ChallengeStatusReceiver_")
@protocol ChallengeStatusReceiver
- (void)completed:(CompletionEvent * _Nonnull)completionEvent;
- (void)cancelled;
- (void)timedout;
- (void)protocolError:(ProtocolErrorEvent * _Nonnull)protocolErrorEvent;
- (void)runtimeError:(RuntimeErrorEvent * _Nonnull)runtimeErrorEvent;
@end


SWIFT_PROTOCOL("_TtP14ipworks3ds_sdk19ClientEventListener_")
@protocol ClientEventListener
- (void)onDataPacketIn:(NSData * _Nonnull)dataPacket;
- (void)onDataPacketOut:(NSData * _Nonnull)dataPacket;
- (void)onError:(int32_t)errorCode :(NSString * _Nonnull)description;
- (void)onLog:(int32_t)logLevel :(NSString * _Nonnull)message :(NSString * _Nonnull)logType;
- (void)onSSLServerAuthentication:(NSData * _Nonnull)certEncoded :(NSString * _Nonnull)certSubject :(NSString * _Nonnull)certIssuer :(NSString * _Nonnull)status :(int32_t * _Nonnull)accept;
- (void)onSSLStatus:(NSString * _Nonnull)message;
@end


SWIFT_CLASS("_TtC14ipworks3ds_sdk15CompletionEvent")
@interface CompletionEvent : NSObject
- (NSString * _Nonnull)getSDKTransactionID SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getTransactionStatus SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC14ipworks3ds_sdk16ConfigParameters")
@interface ConfigParameters : NSObject
- (BOOL)addParamWithGroup:(NSString * _Nullable)group paramName:(NSString * _Nonnull)paramName paramValue:(NSString * _Nullable)paramValue error:(NSError * _Nullable * _Nullable)error;
- (NSString * _Nullable)getParamValueWithGroup:(NSString * _Nullable)group paramName:(NSString * _Nonnull)paramName error:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nullable)removeParamWithGroup:(NSString * _Nullable)group paramName:(NSString * _Nonnull)paramName error:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class DirectoryServerInfo;

SWIFT_CLASS("_TtC14ipworks3ds_sdk23ConfigParametersBuilder")
@interface ConfigParametersBuilder : NSObject
- (nonnull instancetype)initWithDirectoryServerInfoList:(NSArray<DirectoryServerInfo *> * _Nullable)directoryServerInfoList runtimeLicense:(NSString * _Nonnull)runtimeLicense deviceParameterBlacklist:(NSArray<NSString *> * _Nullable)deviceParameterBlacklist clientConfig:(NSArray<NSString *> * _Nullable)clientConfig appBundleID:(NSString * _Nonnull)appBundleID OBJC_DESIGNATED_INITIALIZER;
- (ConfigParameters * _Nullable)buildAndReturnError:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end



SWIFT_CLASS("_TtC14ipworks3ds_sdk19DirectoryServerInfo")
@interface DirectoryServerInfo : NSObject
- (nonnull instancetype)initWithRID:(NSString * _Nonnull)RID publicKey:(NSString * _Nonnull)publicKey CA:(NSString * _Nonnull)CA OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithRID:(NSString * _Nonnull)RID publicKey:(NSString * _Nonnull)publicKey CAs:(NSArray<NSString *> * _Nonnull)CAs OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC14ipworks3ds_sdk12ErrorMessage")
@interface ErrorMessage : NSObject
- (NSString * _Nonnull)getTransactionID SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getErrorCode SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getErrorDescription SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getErrorDetails SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC14ipworks3ds_sdk28GetDefaultDSCAIndirectSymbol")
@interface GetDefaultDSCAIndirectSymbol : NSObject
+ (void)transactionStatusStubCodeLength;
+ (void)threeDSServerTransactionIDWhitelistingInformationText;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

enum LabelType : NSInteger;

SWIFT_CLASS("_TtC14ipworks3ds_sdk18LabelCustomization")
@interface LabelCustomization : Customization
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (void)setHeadingTextColorWithColor:(UIColor * _Nullable)color;
- (BOOL)setHeadingTextFontNameWithFontName:(NSString * _Nullable)fontName error:(NSError * _Nullable * _Nullable)error;
- (BOOL)setHeadingTextFontSizeWithFontSize:(NSInteger)fontSize error:(NSError * _Nullable * _Nullable)error;
- (BOOL)setHeadingTextAlignmentWithTextAlignment:(NSTextAlignment)textAlignment error:(NSError * _Nullable * _Nullable)error;
- (BOOL)setPaddingForLabelType:(enum LabelType)forLabelType edge:(UIEdgeInsets)edge error:(NSError * _Nullable * _Nullable)error;
- (BOOL)setBackgroundColorForLabelType:(enum LabelType)forLabelType color:(UIColor * _Nonnull)color error:(NSError * _Nullable * _Nullable)error;
- (BOOL)setTextColorForLabelType:(enum LabelType)forLabelType color:(UIColor * _Nonnull)color error:(NSError * _Nullable * _Nullable)error;
- (BOOL)setTextFontNameForLabelType:(enum LabelType)forLabelType fontName:(NSString * _Nonnull)fontName error:(NSError * _Nullable * _Nullable)error;
- (BOOL)setTextFontSizeForLabelType:(enum LabelType)forLabelType fontSize:(CGFloat)fontSize error:(NSError * _Nullable * _Nullable)error;
- (UIColor * _Nullable)getHeadingTextColor SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nullable)getHeadingTextFontName SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)getHeadingTextFontSize SWIFT_WARN_UNUSED_RESULT;
- (NSTextAlignment)getHeadingTextAlignment SWIFT_WARN_UNUSED_RESULT;
@end

typedef SWIFT_ENUM(NSInteger, LabelType, open) {
  LabelTypeINFO_HEADER = 0,
  LabelTypeINFO_TEXT = 1,
  LabelTypeINFO_LABEL = 2,
  LabelTypeWHITELIST = 3,
  LabelTypeWHY_INFO = 4,
  LabelTypeWHY_INFO_TEXT = 5,
  LabelTypeEXPANDABLE_INFO = 6,
  LabelTypeEXPANDABLE_INFO_TEXT = 7,
  LabelTypeSELECTION_LIST = 8,
};


SWIFT_CLASS("_TtC14ipworks3ds_sdk12ProgressView")
@interface ProgressView : NSObject
- (void)show;
- (void)close;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14ipworks3ds_sdk18ProtocolErrorEvent")
@interface ProtocolErrorEvent : NSObject
- (ErrorMessage * _Nonnull)getErrorMessage SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getSDKTransactionID SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC14ipworks3ds_sdk17RuntimeErrorEvent")
@interface RuntimeErrorEvent : NSObject
- (NSString * _Nullable)getErrorCode SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getErrorMessage SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM(NSInteger, SecurityEvent, open) {
  SecurityEventROOT = 0,
  SecurityEventTAMPERED = 1,
  SecurityEventINSTALLED_FROM_UNTRUSTED_STORE = 2,
  SecurityEventHOOK = 3,
  SecurityEventEMULATOR = 4,
  SecurityEventDEBUGGING = 5,
  SecurityEventDEBUG_ENABLED = 6,
};

enum Severity : NSInteger;

SWIFT_PROTOCOL("_TtP14ipworks3ds_sdk21SecurityEventListener_")
@protocol SecurityEventListener
- (void)alarm:(enum Severity)severity :(enum SecurityEvent)event;
@end

typedef SWIFT_ENUM(NSInteger, Severity, open) {
  SeverityLOW = 0,
  SeverityMEDIUM = 1,
  SeverityHIGH = 2,
};


SWIFT_CLASS("_TtC14ipworks3ds_sdk20TextBoxCustomization")
@interface TextBoxCustomization : Customization
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (BOOL)setCornerRadiusWithCornerRadius:(NSInteger)cornerRadius error:(NSError * _Nullable * _Nullable)error;
- (NSInteger)getCornerRadius SWIFT_WARN_UNUSED_RESULT;
- (BOOL)setBorderWidthWithBorderWidth:(NSInteger)borderWidth error:(NSError * _Nullable * _Nullable)error;
- (void)setBorderColorWithColor:(UIColor * _Nullable)color;
- (NSInteger)getBorderWidth SWIFT_WARN_UNUSED_RESULT;
- (UIColor * _Nullable)getBorderColor SWIFT_WARN_UNUSED_RESULT;
@end

@class NSBundle;
@class UiCustomization;
@class Transaction;
@class Warning;

SWIFT_CLASS("_TtC14ipworks3ds_sdk15ThreeDS2Service")
@interface ThreeDS2Service : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithBundle:(NSBundle * _Nonnull)bundle OBJC_DESIGNATED_INITIALIZER;
/// The 3DS Requestor App calls the initialize method at the start of the
/// payment stage of a transaction. The app passes configuration parameters,
/// UI configuration parameters, and (optionally) user locale to this method.
/// Note: Until the ThreeDS2Service instance is initialized, it shall be
/// unusable.
/// The following tasks are performed during initialization:
/// <ul>
///   <li>
///     Security checks
///   </li>
///   <li>
///     Collection of device information for all versions of the protocol
///   </li>
/// </ul>
/// that the SDK supports. For more information about the device
/// identification parameters that shall be collected, refer to EMV 3-D
/// Secure SDK - Device Information.
/// Depending on the 3DS Requestor App implementation, a ThreeDS2Service
/// instance is called either during 3DS Requestor App startup as a
/// background task or when a transaction is initiated. The state is
/// maintained until the cleanup method is called.
/// \param configParameters Configuration information that shall be used
/// during initialization. For more information, see Class ConfigParameters.
///
/// \param locale (optional) String that represents the locale for the app’s
/// user interface. For example, the value of locale can be “en_US” in Java.
/// Note: If this parameter is not provided, then the default device locale
/// is used.
///
/// \param uiCustomization (optional) UI configuration information that is
/// used to specify the UI layout and theme. For example, font style and font
/// size. For more information, see Class UiCustomization.
///
/// \param clientEventListener TBD
///
///
/// throws:
///
/// <ul>
///   <li>
///     InvalidInputException: This exception shall be thrown in any of
///     the following scenarios:
///     <ul>
///       <li>
///         configParameters is null.
///       </li>
///       <li>
///         The value of configParameters, locale, or uiCustomization is
///       </li>
///     </ul>
///     invalid.
///     For more information, see Class InvalidInputException.
///   </li>
///   <li>
///     SDKAlreadyInitializedException This exception shall be thrown if
///     the 3DS SDK instance has already been initialized.
///   </li>
///   <li>
///     SDKRuntimeException This exception shall be thrown if an internal
///     error is encountered by the 3DS SDK.
///   </li>
/// </ul>
- (BOOL)initializeWithConfigParameters:(ConfigParameters * _Nullable)configParameters locale:(NSString * _Nullable)locale uiCustomization:(UiCustomization * _Nullable)uiCustomization clientEventListener:(id <ClientEventListener> _Nullable)clientEventListener securityEventListener:(id <SecurityEventListener> _Nullable)securityEventListener error:(NSError * _Nullable * _Nullable)error;
- (Transaction * _Nullable)createTransaction:(NSString * _Nonnull)directoryServerID :(NSString * _Nullable)messageVersion error:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
- (BOOL)cleanupAndReturnError:(NSError * _Nullable * _Nullable)error;
- (NSString * _Nullable)getSDKVersionAndReturnError:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
- (NSArray<Warning *> * _Nullable)getWarningsAndReturnError:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC14ipworks3ds_sdk20ToolbarCustomization")
@interface ToolbarCustomization : Customization
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (void)setBackgroundColorWithColor:(UIColor * _Nullable)color;
- (BOOL)setHeaderTextWithHeaderText:(NSString * _Nullable)headerText error:(NSError * _Nullable * _Nullable)error;
- (BOOL)setButtonTextWithButtonText:(NSString * _Nullable)buttonText error:(NSError * _Nullable * _Nullable)error;
- (UIColor * _Nullable)getBackgroundColor SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nullable)getHeaderText SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nullable)getButtonText SWIFT_WARN_UNUSED_RESULT;
@end

@class UIViewController;

SWIFT_CLASS("_TtC14ipworks3ds_sdk11Transaction")
@interface Transaction : NSObject
- (AuthenticationRequestParameters * _Nullable)getAuthenticationRequestParametersAndReturnError:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
- (BOOL)doChallengeWithRootViewController:(UIViewController * _Nonnull)rootViewController challengeParameters:(ChallengeParameters * _Nonnull)challengeParameters challengeStatusReceiver:(id <ChallengeStatusReceiver> _Nonnull)challengeStatusReceiver timeout:(NSInteger)timeout error:(NSError * _Nullable * _Nullable)error;
- (ProgressView * _Nullable)getProgressViewAndReturnError:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
- (BOOL)closeAndReturnError:(NSError * _Nullable * _Nullable)error;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end







SWIFT_CLASS("_TtC14ipworks3ds_sdk15UiCustomization")
@interface UiCustomization : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (BOOL)setButtonCustomizationWithButtonCustomization:(ButtonCustomization * _Nonnull)buttonCustomization buttonType:(enum ButtonType)buttonType error:(NSError * _Nullable * _Nullable)error;
- (BOOL)setToolbarCustomizationWithToolbarCustomization:(ToolbarCustomization * _Nonnull)toolbarCustomization error:(NSError * _Nullable * _Nullable)error;
- (BOOL)setLabelCustomizationWithLabelCustomization:(LabelCustomization * _Nonnull)labelCustomization error:(NSError * _Nullable * _Nullable)error;
- (BOOL)setTextBoxCustomizationWithTextBoxCustomization:(TextBoxCustomization * _Nonnull)textBoxCustomization error:(NSError * _Nullable * _Nullable)error;
- (ButtonCustomization * _Nonnull)getButtonCustomizationWithButtonType:(enum ButtonType)buttonType SWIFT_WARN_UNUSED_RESULT;
- (ToolbarCustomization * _Nonnull)getToolbarCustomization SWIFT_WARN_UNUSED_RESULT;
- (LabelCustomization * _Nonnull)getLabelCustomization SWIFT_WARN_UNUSED_RESULT;
- (TextBoxCustomization * _Nonnull)getTextBoxCustomization SWIFT_WARN_UNUSED_RESULT;
- (void)setBackgroundWithColor:(UIColor * _Nullable)color;
/// \param position 0 – Right, 1 – Left, 2 – Hide
///
- (void)setInformationZoneIconPosition:(NSInteger)position;
- (void)setBrandingZoneLogoGap:(CGFloat)value;
@end


SWIFT_CLASS("_TtC14ipworks3ds_sdk7Warning")
@interface Warning : NSObject
- (NSString * _Nonnull)getID SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getMessage SWIFT_WARN_UNUSED_RESULT;
- (enum Severity)getSeverity SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop
#endif

#endif
